### ISSUE TITLE
The Google Link is Password protected.

### ISSUE THREAD

**Issue by sidd-kishan** [raspiduino/waq#1]
Please provide the password for the google link.

**Comment by raspiduino** [comment]
Which link? The [arc version](https://drive.google.com/file/d/1AkEPWPXm_N3jzcDk58p2uJbi7HENA2sq/view) or the [7z](https://drive.google.com/file/d/1XmCJDlcITesHN5oW01ySUU1eyLF_fUE-/view) one?

**Comment by raspiduino** [comment]
7z version:

![7z](https://user-images.githubusercontent.com/68118236/122666419-4625fa80-d1d7-11eb-90f0-a14c673f7db1.png)

Arc version:

![arc](https://user-images.githubusercontent.com/68118236/122666446-71104e80-d1d7-11eb-81e9-c15683720e98.png)

None of these require password. And if I remember well, I didn't put password on any of them. Could you please check again? Thanks!

**Comment by sidd-kishan** [comment]
Please try to download this file https://drive.google.com/file/d/1XmCJDlcITesHN5oW01ySUU1eyLF_fUE-/view it needs the password. Please check.

![image](https://user-images.githubusercontent.com/1007208/122672678-804cc780-d1ea-11eb-8352-0425589d525f.png)

![image](https://user-images.githubusercontent.com/1007208/122672694-96f31e80-d1ea-11eb-8d37-a05368e763aa.png)

and i am talking about this password

![image](https://user-images.githubusercontent.com/1007208/122672714-b68a4700-d1ea-11eb-893e-75584973acda.png)

**Comment by raspiduino** [comment]
Hmm. Sorry for that. I will check again.

**Comment by raspiduino** [comment]
OK I see your problem. And the original post's link from the forum (the Mega.nz link) is completely broken, so I guess this is the only resource left.

**Comment by sidd-kishan** [comment]
Does the original post contain any password?

**Comment by raspiduino** [comment]
The original post (not mine) is broken. And I am try to remember my password :)

**Comment by raspiduino** [comment]
The 7z version has error. I will update it later. Now please use the arc version ( or wait for me to upload the zip) and it will be fine. I tested the arc with no error.

**Comment by raspiduino** [comment]
I completely forget the password. I will generate the new image tomorrow. Sorry for that :(( I just did not backup the password

**Comment by sidd-kishan** [comment]
arc file works fine, Please include the QEMU_IMG and QEMU_VARS as mine is crashing.

**Comment by raspiduino** [comment]
> arc file works fine

Arc file works fine? I cannot extract it. How could you?

> Please include the QEMU_IMG and QEMU_VARS as mine is crashing.

It's in [Release](https://github.com/raspiduino/waq/releases/tag/v1.0.0). Google link: https://drive.google.com/file/d/1_qx0gX-EULbVBDpQIdTwp8jT4qCoKbqF/view

Thanks for trying my things!

**Comment by raspiduino** [comment]
Oh my god I remembered the password. It's in the arc's comment. The password is `win10arm64`

**Comment by raspiduino** [comment]
@sidd-kishan could you open it yet?

**Comment by raspiduino** [comment]
Close for now since being inactive :)
