### ISSUE TITLE
This error wasn't descrided: Image format was not specified for 'QEMU_EFI.img'/'QEMU_VARS.img'/'woa_17134.img' and probing guessed raw.....

### ISSUE THREAD

**Issue by Max-RM** [raspiduino/waq#11]
![image](https://github.com/raspiduino/waq/assets/81485476/49703cab-b371-43b0-872c-65462e3a42f6)

C:\Users\Max\Desktop\M\WinARM\vm>arm.bat
WARNING: Image format was not specified for 'QEMU_EFI.img' and probing guessed raw.
         Automatically detecting the format is dangerous for raw images, write operations on block 0 will be restricted.
         Specify the 'raw' format explicitly to remove the restrictions.
WARNING: Image format was not specified for 'QEMU_VARS.img' and probing guessed raw.
         Automatically detecting the format is dangerous for raw images, write operations on block 0 will be restricted.
         Specify the 'raw' format explicitly to remove the restrictions.
WARNING: Image format was not specified for 'woa_17134.img' and probing guessed raw.
         Automatically detecting the format is dangerous for raw images, write operations on block 0 will be restricted.
         Specify the 'raw' format explicitly to remove the restrictions.
C:\Program Files\qemu\qemu-system-aarch64.exe: -drive file=virtio-win-0.1.185.iso,media=cdrom,if=none,id=drivercdrom: Could not open 'virtio-win-0.1.185.iso': ╨Э╨╡ ╤Г╨┤╨░╨╡╤В╤Б╤П ╨╜╨░╨╣╤В╨╕ ╤Г╨║╨░╨╖╨░╨╜╨╜╤Л╨╣ ╤Д╨░╨╣╨╗.

The repository does not tell how to solve such a problem

**Comment by Max-RM** [comment]
ChatGPT helped with this: 
![image](https://github.com/raspiduino/waq/assets/81485476/15ab21f0-1db4-4632-b5d4-3d40dce9dd79)
![image](https://github.com/raspiduino/waq/assets/81485476/5c370ee4-620f-4fa8-8ed4-8edc7ab9aed2)

Now code in bat is:

@echo off
title WOA
"C:\Program Files\qemu\qemu-system-aarch64.exe" ^
-name "Windows 10 on ARM64" ^
-M virt ^
-cpu cortex-a72 ^
-smp 3 ^
--accel tcg,thread=multi ^
-m 2048 ^
-drive file="QEMU_EFI.img",format=raw ^
-drive file="QEMU_VARS.img",format=raw ^
-device VGA ^
-device nec-usb-xhci ^
-device usb-kbd ^
-device usb-mouse ^
-device usb-storage,drive=boot ^
-drive if=none,id=boot,file="woa_17134.img",format=raw ^
-device usb-storage,drive=drivercdrom ^
-drive file="virtio-win-0.1.240.iso",media=cdrom,if=none,id=drivercdrom

But next problem in console is:
![image](https://github.com/raspiduino/waq/assets/81485476/09500a5e-b601-4f3e-85ea-a4fd200a73eb)
I waited 10 minutes for it to start, but nothing literally changed. I even gave the highest priority through the task manager.

(qemu:12776): Gtk-WARNING **: Could not load a pixbuf from /org/gtk/libgtk/theme/Adwaita/assets/bullet-symbolic.svg.
This may indicate that pixbuf loaders or the mime database could not be found.

After installing "gtk3-runtime-3.24.31-2022-01-04-ts-win64.exe" nothing happens in cmd but nothing appears on the screen: 
![image](https://github.com/raspiduino/waq/assets/81485476/f7a4ce80-9f4d-45ab-bdd3-c23ab66ec239)

**Comment by zenden2k** [comment]
> -drive file="QEMU_EFI.img",format=raw ^
> -drive file="QEMU_VARS.img",format=raw ^

This is not correct. Should be:

```
-pflash QEMU_EFI.img ^
-pflash QEMU_VARS.img ^
```

You can ignore these warnings:
```
WARNING: Image format was not specified for 'QEMU_EFI.img' and probing guessed raw.
```

EFI shell appears in a few seconds, you don't have to wait 10 minutes.

```
╨Э╨╡ ╤Г╨┤╨░╨╡╤В╤Б╤П ╨╜╨░╨╣╤В╨╕ ╤Г╨║╨░╨╖╨░╨╜╨╜╤Л╨╣ ╤Д╨░╨╣╨╗
```

Это всего лишь говорит о том, что файл virtio-win-0.1.185.iso не найден :-)
Вижу, что вы исправили.

Но работать эта виртуалка будет безумно неторопливо даже на хорошем железе. 
Надо запастись терпением.

**Comment by raspiduino** [comment]
Hello. `-pflash` should be the correct option.

**Comment by Max-RM** [comment]
> > -drive file="QEMU_EFI.img",format=raw ^
> > -drive file="QEMU_VARS.img",format=raw ^
> 
> This is not correct. Should be:
> 
> ```
> -pflash QEMU_EFI.img ^
> -pflash QEMU_VARS.img ^
> ```
> 
> You can ignore these warnings:
> 
> ```
> WARNING: Image format was not specified for 'QEMU_EFI.img' and probing guessed raw.
> ```
> 
> EFI shell appears in a few seconds, you don't have to wait 10 minutes.
> 
> ```
> ╨Э╨╡ ╤Г╨┤╨░╨╡╤В╤Б╤П ╨╜╨░╨╣╤В╨╕ ╤Г╨║╨░╨╖╨░╨╜╨╜╤Л╨╣ ╤Д╨░╨╣╨╗
> ```
> 
> Это всего лишь говорит о том, что файл virtio-win-0.1.185.iso не найден :-) Вижу, что вы исправили.
> 
> Но работать эта виртуалка будет безумно неторопливо даже на хорошем железе. Надо запастись терпением.

This will not work because of:
C:\Users\Max>"C:\Users\Max\Desktop\M\WinARM\vm\arm.bat"
C:\Program Files\qemu\qemu-system-aarch64.exe: -pflash file=QEMU_EFI.img: Could not open 'file=QEMU_EFI.img': ╨Э╨╡ ╤Г╨┤╨░╨╡╤В╤Б╤П ╨╜╨░╨╣╤В╨╕ ╤Г╨║╨░╨╖╨░╨╜╨╜╤Л╨╣ ╤Д╨░╨╣╨╗.

**Comment by Max-RM** [comment]
> Hello. `-pflash` should be the correct option.

C:\Users\Max>"C:\Users\Max\Desktop\M\WinARM\vm\arm.bat"
C:\Program Files\qemu\qemu-system-aarch64.exe: -pflash file=QEMU_EFI.img: Could not open 'file=QEMU_EFI.img': ╨Э╨╡ ╤Г╨┤╨░╨╡╤В╤Б╤П ╨╜╨░╨╣╤В╨╕ ╤Г╨║╨░╨╖╨░╨╜╨╜╤Л╨╣ ╤Д╨░╨╣╨╗.

**Comment by Max-RM** [comment]
![image](https://github.com/raspiduino/waq/assets/81485476/efc5abc4-4267-409f-aeef-3982d33d5f3d)

**Comment by Max-RM** [comment]
> > -drive file="QEMU_EFI.img",format=raw ^
> > -drive file="QEMU_VARS.img",format=raw ^
> 
> This is not correct. Should be:
> 
> ```
> -pflash QEMU_EFI.img ^
> -pflash QEMU_VARS.img ^
> ```
> 
> You can ignore these warnings:
> 
> ```
> WARNING: Image format was not specified for 'QEMU_EFI.img' and probing guessed raw.
> ```
> 
> EFI shell appears in a few seconds, you don't have to wait 10 minutes.
> 
> ```
> ╨Э╨╡ ╤Г╨┤╨░╨╡╤В╤Б╤П ╨╜╨░╨╣╤В╨╕ ╤Г╨║╨░╨╖╨░╨╜╨╜╤Л╨╣ ╤Д╨░╨╣╨╗
> ```
> 
> Это всего лишь говорит о том, что файл virtio-win-0.1.185.iso не найден :-) Вижу, что вы исправили.
> 
> Но работать эта виртуалка будет безумно неторопливо даже на хорошем железе. Надо запастись терпением.

![image](https://github.com/raspiduino/waq/assets/81485476/297f20a3-66d7-4787-a04b-631db4463b53)

**Comment by Max-RM** [comment]
> Hello. `-pflash` should be the correct option.

Doesnt work

**Comment by Max-RM** [comment]
oh wait. I was should use:
-pflash QEMU_EFI.img ^
-pflash QEMU_VARS.img ^

Instread of:
-pflash file="QEMU_EFI.img",format=raw ^
-pflash file="QEMU_VARS.img",format=raw ^

![image](https://github.com/raspiduino/waq/assets/81485476/d3b59324-c81e-4841-9ef8-10e132e7c8cc)

**Comment by Max-RM** [comment]
here was BSOD related wit drivers then I disabled driver signature checking.
And then got this BSOD: 
![image](https://github.com/raspiduino/waq/assets/81485476/e868f562-28b3-45cd-86b0-8dcc094c63c4)
then this screen appear but now without UEFI shell. Now just infinite load:
![image](https://github.com/raspiduino/waq/assets/81485476/d13b17e7-1665-4ef4-ba46-55f957ea98cb)

**Comment by Max-RM** [comment]
I cant disable driver signature because OS will reboot into another BSOD and then OS will forgot that Driver sig was disabled

Stop code: ACPI BIOS ERROR

**Comment by Max-RM** [comment]
@raspiduino @zenden2k

**Comment by raspiduino** [comment]
> @raspiduino @zenden2k

Try `-M virt-2.12`. Also, this repo is outdated, please refer to readme.md for more info

**Comment by Max-RM** [comment]
> > @raspiduino @zenden2k
> 
> Try `-M virt-2.12`. Also, this repo is outdated, please refer to readme.md for more info

MANY THANKSFOR YOU!
![image](https://github.com/raspiduino/waq/assets/81485476/474c7035-dc7c-4437-953f-92395cccf409)

I will leave my bat code here for everyone who will got same error:

@echo off
title WOA
"C:\Program Files\qemu\qemu-system-aarch64.exe" ^
-name "Windows 10 on ARM64" ^
-M virt-2.12 ^
-cpu cortex-a72 ^
-smp 3 ^
--accel tcg,thread=multi ^
-m 3072 ^
-pflash QEMU_EFI.img ^
-pflash QEMU_VARS.img ^
-device VGA ^
-device nec-usb-xhci ^
-device usb-kbd ^
-device usb-mouse ^
-device usb-storage,drive=boot ^
-drive if=none,id=boot,file="woa_17134.img",format=raw ^
-device usb-storage,drive=drivercdrom ^
-drive file="virtio-win-0.1.240.iso",media=cdrom,if=none,id=drivercdrom

**Comment by raspiduino** [comment]
> > > @raspiduino @zenden2k
> > 
> > 
> > Try `-M virt-2.12`. Also, this repo is outdated, please refer to readme.md for more info
> 
> MANY THANKSFOR YOU! ![image](https://private-user-images.githubusercontent.com/81485476/323500436-474c7035-dc7c-4437-953f-92395cccf409.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MjUyNTksIm5iZiI6MTcxMzQyNDk1OSwicGF0aCI6Ii84MTQ4NTQ3Ni8zMjM1MDA0MzYtNDc0YzcwMzUtZGM3Yy00NDM3LTk1M2YtOTIzOTVjY2NmNDA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDA3MjIzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxZjVjYWQ1NmE1N2RhNDBlNTJlNTlmZjZhMGNlZTk3MjY0NjdiYmNmZmY0N2NlZmM1ZjBiMDNkMDlhOWQ1NTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.InNPMdDZPBqEvRaOjNWbHdZWaBf_hXYK3BI-Fbps1SQ)
> 
> I will leave my bat code here for everyone who will got same error:
> 
> @echo off title WOA "C:\Program Files\qemu\qemu-system-aarch64.exe" ^ -name "Windows 10 on ARM64" ^ -M virt-2.12 ^ -cpu cortex-a72 ^ -smp 3 ^ --accel tcg,thread=multi ^ -m 3072 ^ -pflash QEMU_EFI.img ^ -pflash QEMU_VARS.img ^ -device VGA ^ -device nec-usb-xhci ^ -device usb-kbd ^ -device usb-mouse ^ -device usb-storage,drive=boot ^ -drive if=none,id=boot,file="woa_17134.img",format=raw ^ -device usb-storage,drive=drivercdrom ^ -drive file="virtio-win-0.1.240.iso",media=cdrom,if=none,id=drivercdrom

Glad it works for you. I just randomly remembered the flag and didn't expect it to work but yeah, it works.

**Comment by Max-RM** [comment]
> Glad it works for you. I just randomly remembered the flag and didn't expect it to work but yeah, it works.

Btw why keyboard doesnt work correctly?

**Comment by raspiduino** [comment]
> Btw why keyboard doesnt work correctly?

Wdym?

**Comment by Max-RM** [comment]
> > Btw why keyboard doesnt work correctly?
> 
> Wdym?

When I pressed buttons, nothing happen in WinARM

**Comment by Max-RM** [comment]
Also need to search how to make shared folder

**Comment by raspiduino** [comment]
> > > Btw why keyboard doesnt work correctly?
> > 
> > 
> > Wdym?
> 
> When I pressed buttons, nothing happen in WinARM

IDK, it worked the last time I tested it (several years ago)

**Comment by Max-RM** [comment]
> IDK, it worked the last time I tested it (several years ago)

It worked now. Idk why didnt work before

**Comment by raspiduino** [comment]
> > IDK, it worked the last time I tested it (several years ago)
> 
> It worked now. Idk why didnt work before

Bruh, instead of logging your tries here in realtime, you can try yourself and then comment later.

**Comment by Max-RM** [comment]
> > > IDK, it worked the last time I tested it (several years ago)
> > 
> > 
> > It worked now. Idk why didnt work before
> 
> Bruh, instead of logging your tries here in realtime, you can try yourself and then comment later.

ok

**Comment by Max-RM** [comment]
> > > IDK, it worked the last time I tested it (several years ago)
> > 
> > 
> > It worked now. Idk why didnt work before
> 
> Bruh, instead of logging your tries here in realtime, you can try yourself and then comment later.

Do you have pre-installed .iso with working PowerShell? Because in this iso, which is provided in this repository, PowerShell does not work (all 4 PowerShell doesnt work).

**Comment by raspiduino** [comment]
> > > > IDK, it worked the last time I tested it (several years ago)
> > > 
> > > 
> > > It worked now. Idk why didnt work before
> > 
> > 
> > Bruh, instead of logging your tries here in realtime, you can try yourself and then comment later.
> 
> Do you have pre-installed .iso with working PowerShell? Because in this iso, which is provided in this repository, PowerShell does not work (all 4 PowerShell doesnt work).

I don't think so. But you can try install on your own, there is a link to a gist in the readme. You may have better luck trying that.
