### ISSUE TITLE
Windows 10 ARM iso hung at the boot screen

### ISSUE THREAD

**Issue by nguyenthienminh** [raspiduino/waq#2]
Yeah, the installer got hung at the boot logo for a long time. I left it for hours and still nothing. Any ideas? 
![image](https://user-images.githubusercontent.com/86407326/148148050-ef82176a-4866-47d8-9f4e-db40e92a2895.png)

**Comment by raspiduino** [comment]
Hello and welcome to the repo!
- Which version of Windows ARM are you using (like the build, ...)? Can you provide more details like where did you get the iso from (did you make it using uupdump.ml or you got it from the internet).
- Can you provide the QEMU version, the command line that you passed to QEMU?

Thank you!

**Comment by nguyenthienminh** [comment]
Update: I happened to use the newer version of 10 ARM (version 2004) which doesn't work. I had to use version 1909 to make it work, but it still BSODs when booting the installer with a ACPI_ERROR blue screen. I looked in the BIOS and the RAM amount reported is 0MB.
Also, more info:
- QEMU Version is the version from July 11th 2018;
- Machine is "virt-3.0";
- The cmdline is: `qemu-system-aarch64.exe ^
-M virt-2.9 ^
-cpu cortex-a57 ^
-smp 3 ^
-m 3072M ^
-pflash QEMU_EFI.img ^
-pflash QEMU_VARS.img ^
-device VGA ^
-device nec-usb-xhci ^
-device usb-kbd ^
-device usb-mouse ^
-device usb-storage,drive=install ^
-drive if=none,id=install,format=raw,media=cdrom,file=.\WindowsARM.iso ^
-device usb-storage,drive=drivers ^
-drive if=none,id=drivers,readonly=on,file=.\drivers.vhdx ^
-device virtio-blk,drive=system ^
-drive if=none,id=system,format=raw,file=.\system.vhdx
`
- I got the UEFI firmware from another website: https://withinrafael.com/2018/02/12/boot-arm64-builds-of-windows-10-in-qemu/
Direct link to the firmware: https://1drv.ms/f/s!AnjdAnZZcu-GpIJqZ9-B_jSpmDw3Ng.

**Comment by raspiduino** [comment]
Well, I also tried that firmware (some years ago) but if you feel is just old for now, you can get the new prebuilt UEFI firmware online. You can get one from [here](https://retrage.github.io/edk2-nightly/). Remember to choose AARCH64 version for QEMU.

Also, there is a bug in qemu `virt` machine (this have been fixed in 5.x). You said you use the QEMU from 2018, so it's equal to version 3.x. In that case, `virt-2.12` seems to work for Windows ARM. If it still results in error, try disabling `highmem` and enable EL2 by using `-machine virt-2.12,highmem=off,virtualization=on` and see if it works. (I wonder why you choose this QEMU version)

I have read somewhere (didn't remember to save the link, sorry) that Windows 20H1 arm64 and later doesn't work on QEMU without KVM (virtualization, not emulation). So if you want some recent Windows arm64 on QEMU, you should use KVM (you can try on some hardware like RPi and other SBCs)

Also, you should change the display from `VGA` to `ramfb`, as `VGA` is usually for x86 emulation. `-device VGA` to `-device ramfb`.

Again, try this:
```batch
qemu-system-aarch64.exe ^
-M virt-2.12,highmem=off,virtualization=on^
-cpu cortex-a57 ^
-smp 3 ^
-m 3072M ^
-pflash QEMU_EFI.img ^
-pflash QEMU_VARS.img ^
-device ramfb^
-device nec-usb-xhci ^
-device usb-kbd ^
-device usb-mouse ^
-device usb-storage,drive=install ^
-drive if=none,id=install,format=raw,media=cdrom,file=.\WindowsARM.iso ^
-device usb-storage,drive=drivers ^
-drive if=none,id=drivers,readonly=on,file=.\drivers.vhdx ^
-device virtio-blk,drive=system ^
-drive if=none,id=system,format=raw,file=.\system.vhdx
```
Try this and see if it works! Thank you for taking a look at this repo and feel free to ask about this.

**Comment by nguyenthienminh** [comment]
The BIOS file kind of got really corrupted and such caused this error when executed the cmdline: 
![image](https://user-images.githubusercontent.com/86407326/148345233-1ba9eae6-7c1c-43d6-86a5-ff9f03698494.png)
If I use the old BIOS, the cmdline will (once executed) got this error: 
![image](https://user-images.githubusercontent.com/86407326/148345369-77e85b42-a08e-4b6e-a213-d7e826b5b51c.png)
And yes, if the video card's emulation files are not found, then the machine won't start again: 
![image](https://user-images.githubusercontent.com/86407326/148345437-ff96f2e7-0af4-4cb6-b640-68e34c4f8ea7.png)

**Comment by raspiduino** [comment]
No it is *not* corrupted, it just not fit the QEMU's flash. The QEMU's flash is 64MB in size and you should have the firmware also in 64 MB.

From [this](https://station.eciton.net/uefi-for-armarm64-on-qemu.html), on linux you can use `dd if=/dev/zero bs=1M count=64 of=QEMU_EFI.img` and then `dd if=QEMU_EFI.fd bs=1M of=flash0.img conv=notrunc`.

On Windows you can use `fsutil file createnew QEMU_EFI.img 67108864` to create a 64MB file and then use some hex editor you can copy the content of QEMU_EFI.fd to the beginning of the new file. QEMU will happily accept it.

**Comment by nguyenthienminh** [comment]
Oh well, it still works, so yeah. It's currently at the installer, which is going to take not a long time (maybe). I sped it up using GVM (KVM for Windows) too, so yeah, it's going to be a little bit faster.

**Comment by raspiduino** [comment]
Oh man, which platform are you running on? Is your host platform x86 or ARM?

**Comment by nguyenthienminh** [comment]
Woopsie. Let me uninstall GVM.

**Comment by raspiduino** [comment]
Excuse me, can you provide the link to GVM? I have googled it but couldn't find any information. Thanks!

**Comment by nguyenthienminh** [comment]
Here's the link: http://github.com/google/Android-emulator-hypervisor-driver-for-amd-processors

**Comment by raspiduino** [comment]
Thanks! Is your VM ok now?

**Comment by nguyenthienminh** [comment]
Well, it booted the installer successfully, but it didn't detect the hard drive at all. Even after loading the driver, it still only appear a tiny 60MB volume on the "Choose a partition to install Windows" screen.

**Comment by raspiduino** [comment]
The line `-drive if=none,id=system,format=raw,file=.\system.vhdx`
Try changing it to `format=vhdx` and see if something better

**Comment by nguyenthienminh** [comment]
That fixed it. Thanks!

**Comment by raspiduino** [comment]
Good to see it works! If you have any other questions, feel free to put a comment here. Thanks!

**Comment by nguyenthienminh** [comment]
Oh. So now it's really stuck at the "Installing updates" screen for 30 mins already:
![image](https://user-images.githubusercontent.com/86407326/148487572-13fb6a46-e2d9-457f-8eb1-16e13d98c82d.png)

**Comment by nguyenthienminh** [comment]
Oh nevermind, it's unhung anyways

**Comment by raspiduino** [comment]
You should be patient. Emulation is always slower than you expected.

If you want to know is things in process (eg if is hang or not), you can press <kbd>Shift</kbd>+<kbd>F10</kbd> to open cmd and then open task manager from it.

**Comment by nguyenthienminh** [comment]
Yeah, I opened the taskmgr like that, and.... the CPU got capped at 100%, that's why it's so slow

**Comment by nguyenthienminh** [comment]
oh, and it refused to boot from the hard drive. It only wants to boot from the DVD.

**Comment by raspiduino** [comment]
Ok you should remove the cd from qemu. Or you can go to firmware setting and choose to boot from hard drive

**Comment by nguyenthienminh** [comment]
Yep, I go into the firmware settings, chose the hard drive and it refused to boot. Just exited out to the BIOS screen. When I removed the DVD, it wants to network boot.

**Comment by raspiduino** [comment]
Is the installer show some errors or it just ask you to reboot?

**Comment by nguyenthienminh** [comment]
Oh nevermind, by a little probing found out the device name. The BIOS menu is just so messy...

**Comment by raspiduino** [comment]
Try all of the option and you will find the one correct :)

**Comment by nguyenthienminh** [comment]
I saved the statistics into a .txt file, once the install's done i'm going to upload the statistics up here

**Comment by nguyenthienminh** [comment]
Can I let my computer sleep when the VMs doing this? I have to go to another place so yeah. ![image](https://user-images.githubusercontent.com/86407326/148491861-e6864c43-6245-48a7-8660-df1a1ae0e5f0.jpeg)

**Comment by raspiduino** [comment]
You have to keep your computer on, of course.

**Comment by nguyenthienminh** [comment]
oh, I already let it slept for... a while, and it kind of pauses the vm, but starting it up'll basically unpause it.

**Comment by nguyenthienminh** [comment]
Huh, now it got stuck on the "Just a moment..." screen for a whole 2 hours (not included the time I let the computer hibernate, which is roughly 14 hours). Sometimes the VGA output got black, but moving the cursor kind of un-blacks it. 
![image](https://user-images.githubusercontent.com/86407326/148628817-577c21a4-d362-45e2-a2be-34de38ac4a20.png)

**Comment by raspiduino** [comment]
Well, black is normal, it just show black when you leave it for a long time, it will turn off the screen.

Keep the installer for some more time, and if the loop is endless, I will show you the way to bypass OOBE. (Sometimes QEMU is just to slow)

**Comment by nguyenthienminh** [comment]
Yeah, it's 2 hours. I know how to skip OOBE mind you, so should I reboot the VM?

**Comment by raspiduino** [comment]
If you reboot the VM, it will show the error "please start the installation process again" or it will result in the endless loop again

**Comment by nguyenthienminh** [comment]
I knew that, I'm skipping the OOBE using the registry.

**Comment by raspiduino** [comment]
After get to the desktop, if you find the VM to slowly, you can try some optimize script on github for Windows ARM. Just search on google :)

**Comment by nguyenthienminh** [comment]
Automatic Repair just crashed the entire VM. Now it's time to disable WinRE.

**Comment by nguyenthienminh** [comment]
Well, after all that (I even skipped the OOBE), it still got stuck at the "Just a moment..." screen.

**Comment by nguyenthienminh** [comment]
oh. now it's this. 
![image](https://user-images.githubusercontent.com/86407326/148671093-0f80c326-289a-483c-b534-e2afa7c56a85.png)

**Comment by raspiduino** [comment]
Change `-device virtio-blk,drive=system` to `-device usb-storage,drive=system`

**Comment by nguyenthienminh** [comment]
That certainly fixed the problem. However, I had to change the boot order. I also tweaked the res a little bit from 800x600 to 1024x768 in the BIOS so it looked more great in there.

**Comment by nguyenthienminh** [comment]
And Windows kept booting and hanging at the spinning animation

**Comment by raspiduino** [comment]
Spinning? The boot screen with Windows logo?

**Comment by nguyenthienminh** [comment]
Yeah. It is hanging there really, but the spinner is still spinning.

**Comment by raspiduino** [comment]
Have you boot to the desktop yet? (Since you skipped OOBE?

**Comment by nguyenthienminh** [comment]
Nope, I had to do a full reinstall (using dism), because the normal way got stuck at the "Just a moment..." waiting screen.

**Comment by nguyenthienminh** [comment]
Oh anyways, QEMU is just so slow, now it finally booted.

**Comment by raspiduino** [comment]
How did you use dism? Can you post your command here (like how you create partition and format it then apply boot file and apply with dism?)

**Comment by raspiduino** [comment]
Be patient! :)

**Comment by nguyenthienminh** [comment]
It's so slow!!!!!!!!!! (I reached the desktop but Explorer hasn't even loaded finished)

**Comment by raspiduino** [comment]
Buy an ARM-based SBC and run KVM on it (I currently do that) and it is much better

**Comment by nguyenthienminh** [comment]
Explorer is literally crashing constantly because of the high CPU load.

**Comment by raspiduino** [comment]
If it is too slow, try booting to safe mode!

**Comment by nguyenthienminh** [comment]
The specs are done!
[10ARMStatistics.txt](https://github.com/raspiduino/waq/files/7843122/10ARMStatistics.txt)

**Comment by raspiduino** [comment]
If you have no more problems, please close the issue. If not, comment here and I will happily help you :)
