### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by ThePolishLemon** [raspiduino/waq#5]
Hey the link to the mega page is dead
![Screenshot_20220707-230110_Chrome](https://user-images.githubusercontent.com/82435316/177871240-25a92fe1-bf76-4173-9343-91a2e18ed7cc.png)

**Comment by raspiduino** [comment]
Maybe the author of that link removed it. What do you want to get from it?

**Comment by ThePolishLemon** [comment]
i want tto get this https://cdn.upload.systems/uploads/K7EJUxI1.png

**Comment by ThePolishLemon** [comment]
> Maybe the author of that link removed it. What do you want to get from it?

all listed in the github page

**Comment by ThePolishLemon** [comment]
OH I AM DUMB ITS IN THE RELEASE 🤣

**Comment by raspiduino** [comment]
Sorry for late reply but you have found the answer by yourself! Thanks for taking a look at the repo!
