### ISSUE TITLE
Windows failed to start . A recent hadrware or software change might be the cause

### ISSUE THREAD

**Issue by ThePolishLemon** [raspiduino/waq#6]
![nxplayer bin_9uMTptRoTN](https://user-images.githubusercontent.com/82435316/178024287-4ddc2250-17ef-468f-97ec-eb766c9aba4b.png)

Note : i deleted the -device VGA because it was giving me the error - failed to find romfile "vgabios-stdvga.bin"

**Comment by raspiduino** [comment]
You need to disable signature check. Please enter the recovery screen, select boot option and select disable signature vertify.

Reason: rpi drivers aren't signed

I will soon upload a new OS image that no longer have this issue.

Thank you!

**Comment by ThePolishLemon** [comment]
> You need to disable signature check. Please enter the recovery screen, select boot option and select disable signature vertify.
> 
> Reason: rpi drivers aren't signed
> 
> I will soon upload a new OS image that no longer have this issue.
> 
> Thank you!

How would i go about entering the recovery screen , srry for being dumb

**Comment by raspiduino** [comment]
It has been a long time I haven't use Windows Recovery menu, so I will tell you the step and you do it and capture the screen back to me so I can tell you the next step, is that ok?

Now with the above screen in your picture, you should press <kbd>enter</kbd>. If you are not in that screen, please send the new image to me.

Thank you!

**Comment by raspiduino** [comment]
Not related but
> failed to find romfile "vgabios-stdvga.bin"
Are you on Linux or Windows?

**Comment by ThePolishLemon** [comment]
> Not related but
> 
> > failed to find romfile "vgabios-stdvga.bin"
> 
> Are you on Linux or Windows?

Linux

**Comment by ThePolishLemon** [comment]
> 

Ok hold on a sec

**Comment by raspiduino** [comment]
> > Not related but
> > > failed to find romfile "vgabios-stdvga.bin"
> > 
> > 
> > Are you on Linux or Windows?
> 
> Linux

Go to https://github.com/qemu/qemu, search for that file (using `go to file`), then copy to `/usr/share/qemu` and see if it works. Or you can pass `-L` to command line to indicate the directory to look for firmware file.

**Comment by ThePolishLemon** [comment]
> > > Not related but
> > > > failed to find romfile "vgabios-stdvga.bin"
> > > 
> > > 
> > > Are you on Linux or Windows?
> > 
> > 
> > Linux
> 
> Go to https://github.com/qemu/qemu, search for that file (using `go to file`), then copy to `/usr/share/qemu` and see if it works. Or you can pass `-L` to command line to indicate the directory to look for firmware file.

Thx, i will send a vid of what happened when I get my mouse , wait a sec for now

**Comment by ThePolishLemon** [comment]
Now i am stuck at the windows logo with please wait

> > > Not related but
> > > > failed to find romfile "vgabios-stdvga.bin"
> > > 
> > > 
> > > Are you on Linux or Windows?
> > 
> > 
> > Linux
> 
> Go to https://github.com/qemu/qemu, search for that file (using `go to file`), then copy to `/usr/share/qemu` and see if it works. Or you can pass `-L` to command line to indicate the directory to look for firmware file.

**Comment by ThePolishLemon** [comment]
> Now i am stuck at the windows logo with please wait
> 
> > > > Not related but
> > > > > failed to find romfile "vgabios-stdvga.bin"
> > > > 
> > > > 
> > > > Are you on Linux or Windows?
> > > 
> > > 
> > > Linux
> > 
> > 
> > Go to https://github.com/qemu/qemu, search for that file (using `go to file`), then copy to `/usr/share/qemu` and see if it works. Or you can pass `-L` to command line to indicate the directory to look for firmware file.
Turns out the PC crashed lemme reboot it

**Comment by raspiduino** [comment]
> > Now i am stuck at the windows logo with please wait
> > > > > Not related but
> > > > > > failed to find romfile "vgabios-stdvga.bin"
> > > > > 
> > > > > 
> > > > > Are you on Linux or Windows?
> > > > 
> > > > 
> > > > Linux
> > > 
> > > 
> > > Go to https://github.com/qemu/qemu, search for that file (using `go to file`), then copy to `/usr/share/qemu` and see if it works. Or you can pass `-L` to command line to indicate the directory to look for firmware file.
> 
> Turns out the PC crashed lemme reboot it

If possible, please send me image, or video. Thanks!

**Comment by ThePolishLemon** [comment]
![Uploading IMG_20220709_125502.jpg…]()
That is the same signature error , just a bit different screen , what to do

**Comment by ThePolishLemon** [comment]
> > > Now i am stuck at the windows logo with please wait
> > > > > > Not related but
> > > > > > > failed to find romfile "vgabios-stdvga.bin"
> > > > > > 
> > > > > > 
> > > > > > Are you on Linux or Windows?
> > > > > 
> > > > > 
> > > > > Linux
> > > > 
> > > > 
> > > > Go to https://github.com/qemu/qemu, search for that file (using `go to file`), then copy to `/usr/share/qemu` and see if it works. Or you can pass `-L` to command line to indicate the directory to look for firmware file.
> > 
> > 
> > Turns out the PC crashed lemme reboot it
> 
> If possible, please send me image, or video. Thanks!
> 
> You can paste image and video here, either by drag and drop or CTRL C, CTRL V

![Uploading IMG_20220709_125502.jpg…]()

**Comment by ThePolishLemon** [comment]
Why does the image not upload

**Comment by ThePolishLemon** [comment]
Lemme upload it to imgur

**Comment by ThePolishLemon** [comment]
https://imgur.com/a/lZS8lIj

**Comment by raspiduino** [comment]
Press F8

**Comment by ThePolishLemon** [comment]
Got win 10 running flawlessly thx man

**Comment by raspiduino** [comment]
Ok no problem! Great to see it worked!
